### ISSUE TITLE
Doc Does not specify where is VoodooTrackpoint...

### ISSUE THREAD

**Issue by amitchaudhari9121** [VoodooSMBus/VoodooRMI#107]
This is a great Project! I got my trackpad gestures working. 

But the physical buttons on the trackpad are not working. (they were working on the previous voodooPS2mouse kext)

I could not find the voodooTrackpoint kext this line below mentions. It's not inside voodooRMI.kext as the readme suggests

> For OpenCore users, make sure to add VoodooInput, VoodooTrackpoint and RMISMBus/RMII2C to your Config.plist.

Do I have to compile it separately?
Am I looking at the wrong place?

**Comment by amitchaudhari9121** [comment]
I solved my issue!

It seems that trackpoint kext was removed in 1.3. so I rolledback to kexts from version 1.2 release and it works flawlessly now.

could you please update the docs?

Either mention version specifics (opencore users use 1.2, or something like that), or add an extra note about trackpoint?

**Comment by 1Revenger1** [comment]
I guess I forgot to remove it from the docs - I'll update it at some point in the next couple days.

It got merged into VoodooInput, so it is not required anymore. The trackpoint should still work normally.

**Comment by amitchaudhari9121** [comment]
It did not work though,
Trackpoint was not working at all , and the physical buttons on top of tracpad were not working as well. rolled back and both started working just fine. 

I am fairly new to this hackintosh (this is my first time 😊 ) 
But I once opened my specific laptop (ThinkPad X1C3 2015) down to every part. and the trackpoint is a separate module completely. So maybe, it needed a separate entry in the config.plist. Complete Speculation on my point though. I don't even know how would i should go about confirming it though...

I'd love to investigate further !!!

**Comment by 1Revenger1** [comment]
It requires you to use the VoodooInput from VoodooRMI, or atleast an up to date version of VoodooInput. Make sure it isn't one from a really old version of VoodooPS2 or an old version that you put in yourself.

**Comment by amitchaudhari9121** [comment]
Pull request #108 addresses this now . 

Thankyou!
