### ISSUE TITLE
Thinkpad L14 Gen 1 - Tracking issues when swiping fast and tapping (maybe a rejection issue?)

### ISSUE THREAD

**Issue by Caipe97** [VoodooSMBus/VoodooRMI#115]
**Describe the bug**
Using VoodooRMI in SMBUS mode on a Thinkpad L14 Gen 1, the touchpad tracking is inaccurate when swiping fast, and taps are usually rejected.

macOS Big Sur 11.2.2

doing a cat /proc/bus/input/devices on Linux I get this info from the touchpad:

I: Bus=0011 Vendor=0002 Product=0007 Version=01a1
N: Name="SynPS/2 Synaptics TouchPad"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input5
U: Uniq=
H: Handlers=mouse0 event4 
B: PROP=5
B: EV=b
B: KEY=e520 10000 0 0 0 0
B: ABS=660800011000003

**To Reproduce**
1. Install VoodooPS2Controller
2. Install VoodooRMI 1.3.3 with included VoodooSMBUS (disabling I2C kexts as in guide)
3. Try to use the touchpad while swiping fast with one or many fingers

**Expected behavior**
Tracking should be accurate and should not be rejected

**Log**
[log.txt](https://github.com/VoodooSMBus/VoodooRMI/files/6448369/log.txt)
I used the debug version of VoodooRMI to capture the log while doing the following gestures, aided by FingerMgmt:

Swiping to any direction with one finger:
![GIF-210509_173835](https://user-images.githubusercontent.com/56038124/117586524-14594880-b0ef-11eb-8868-00e61f8db26b.gif)

It works fine if the gesture isn't quick:
![ezgif-2-247df1e9929f](https://user-images.githubusercontent.com/56038124/117586455-b3ca0b80-b0ee-11eb-8a94-6e3bd7d1dcd2.gif)

Tapping is also troublesome:
![ezgif-2-63da13105bba](https://user-images.githubusercontent.com/56038124/117586434-8da46b80-b0ee-11eb-8820-c58a4485084e.gif)

**Comment by Caipe97** [comment]
Update: Testing the Debug version VoodooRMI-1.3.2-NO_Z_NO_SHAPE from issue #100 seems to make the touchpad work normally. However, while using it I get huge power spikes (possibly because of the constant debugging messages).

Any insights?

**Comment by 1Revenger1** [comment]
Sorry that I haven't replied
Is the newest version here any better?
https://dortania.github.io/builds/?product=VoodooRMI&viewall=true
The palm rejection should be reworked, with the conditions I removed in NO_Z_NO_SHAPE relaxed.

**Comment by Caipe97** [comment]
I find that it works pretty good, though the touchpad tracking has become quite stuttery, still bearable tho... Could it be related to battery patching?

**Comment by 1Revenger1** [comment]
hrmm, it depends. If your using ACPIBatteryManager, and the _STA method for your battery includes a wait, it could be. If not, I honestly don't have any clues. Is it any better in the center vs the edges?

**Comment by 1Revenger1** [comment]
If you want to try another version of VoodooSMBus, you could try this
[VoodooSMBus.kext.zip](https://github.com/VoodooSMBus/VoodooRMI/files/7190738/VoodooSMBus.kext.zip)
This changes how interrupts work a bit, though I haven't really noticed any difference on my machine.

**Comment by Caipe97** [comment]
I've tried the latest version and the cursor isn't still quite as smooth as with VoodooPS2. Tested version 1.3.5 from your link + your VoodooSMBus kext. I'm using SMCBatteryManager and my DSDT patch, I'll get back with details when I have the time. Gestures work perfectly. Definitely an improvement over what 1.3.3 was.

**Comment by 1Revenger1** [comment]
Hrmm, I know that someone else at some point had run into a similar thing in Linux. Something to do with the reporting rate of the trackpad. I'm not sure if there's a way I can change reporting rate though, not super familiar with the F12 function.

**Comment by 1Revenger1** [comment]
[VoodooRMI-1.3.4-DEBUG-Read-reportrate-bit.zip](https://github.com/VoodooSMBus/VoodooRMI/files/7272370/VoodooRMI-1.3.4-DEBUG-Read-reportrate-bit.zip
[VoodooRMI-1.3.4-DEBUG-Set-Bit.zip](https://github.com/VoodooSMBus/VoodooRMI/files/7272373/VoodooRMI-1.3.4-DEBUG-Set-Bit.zip)
)

I'd be interested to see what happens if you try both of those versions. For the first version, look under the properties of F01->PowerProperties in ioreg and see what the report rate bit is set to. The second version sets the bit to 1. No clue if that will change anything though.

**Comment by Caipe97** [comment]
The first version gives this info in ioreg:
![imagen](https://user-images.githubusercontent.com/56038124/135931814-234a4a7a-53a8-4193-ba92-b59712efbf41.png)

These are all the available functions my touchpad supports, if you need a bit more context..:
![imagen](https://user-images.githubusercontent.com/56038124/135931955-1e9da32e-0df4-4dc1-9028-a0792132757d.png)

Going to test the second version...

**Comment by Caipe97** [comment]
I've found no difference using any of the versions regarding improvements... What I found is that the tracking feels very much like using the Thinkpad nub/trackpoint (which I've always found "jumpier" than the main touchpad)
