### ISSUE TITLE
Support for SYNA7DB5.

### ISSUE THREAD

**Issue by afkniladri** [VoodooSMBus/VoodooRMI#130]
Going through the readme I came across that my device wasn't supported. Hence I raised an issue. Thanks.

**Comment by 1Revenger1** [comment]
The list isn't complete. Does SYNA7DB5 work with VoodooRMI? Could add it to the list if you want.

**Comment by afkniladri** [comment]
Yes please do. Btw mine is I2C based working with (SSDT-XOSI)[https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad.html]. VoodooI2CHID works for me, synaptics.kext doesn't. Providing the details if it helps.

(MY REPOSITORY)[https://github.com/afkniladri/Acer-Nitro5-Hackintosh-OC]

**Comment by 1Revenger1** [comment]
Do you know which Trackpad function it uses? It'll either be F11/F12 and it'll be attached to RMIBus in IORegistryExplorer.

**Comment by afkniladri** [comment]
Sorry but how to check it ? This is all I hav
![Screenshot 2021-09-19 at 8 47 05 PM](https://user-images.githubusercontent.com/31654012/133932906-41630e3d-1233-4d92-9550-57ebf031faea.png)
e.

**Comment by 1Revenger1** [comment]
You'll only see it when using VoodooRMI

**Comment by afkniladri** [comment]
Ok. I'll report to you soon.

**Comment by afkniladri** [comment]
Should I disable VoodooI2CHID.kext ?

**Comment by 1Revenger1** [comment]
No you don't need to. VoodooRMI has a higher probe score than it.

**Comment by afkniladri** [comment]
Sorry but what about VoodooI2CServices.kext and VoodooInput.kext (VoodooI2C) ? should I disable

**Comment by 1Revenger1** [comment]
VoodooI2C depends on VoodooI2CServices, so keep that no matter what.
Use the VoodooInput from VoodooRMI, disable the one in VoodooI2C

**Comment by afkniladri** [comment]
ok.

**Comment by afkniladri** [comment]
Still no RMIBUS in IORegistry , trackpad works. But when I disable I2CHID trackpad won't work.

**Comment by 1Revenger1** [comment]
May not work with it then, could look to see what the logging says. Add `msgbuf=1048576` to your boot-args, then use `sudo dmesg | grep -i "VRMI" > ~/Desktop/vrmi_log.txt` once you've rebooted and are in the macOS terminal

**Comment by afkniladri** [comment]
can I share my config.plist with you ? You can lead me where I'm going wrong
[config.plist.zip](https://github.com/VoodooSMBus/VoodooRMI/files/7192452/config.plist.zip)

**Comment by 1Revenger1** [comment]
VoodooRMI should be before RMII2C.kext

**Comment by afkniladri** [comment]
![Screenshot 2021-09-22 at 4 18 17 PM](https://user-images.githubusercontent.com/31654012/134330708-197482f2-d859-4e49-9e64-14490a35c518.png)

Excuse me but where to look for F11/F12 functionality ?

**Comment by afkniladri** [comment]
![Screenshot 2021-09-22 at 4 42 03 PM](https://user-images.githubusercontent.com/31654012/134333666-b02937d4-91d5-491a-89a1-f9f428670b1b.png)

**Comment by afkniladri** [comment]
Working perfectly fine except the fact that when I test out the rejection on palm detection. It breaks the system. The trackpad won't anymore, ofc till next boot.

**Comment by afkniladri** [comment]
Main Function is F12 . Just to confirm.
![Screenshot 2021-09-22 at 4 53 16 PM](https://user-images.githubusercontent.com/31654012/134335109-f949e591-8474-4343-a61f-716578b50c38.png)

**Comment by 1Revenger1** [comment]
hrmm, that's kinda weird
can you provide a log?

**Comment by afkniladri** [comment]
Nevermind .. after a few tweaks with the configuration (palmRejectionWidth specifically). A bit of tweaks here and there it would be flawless, just like windows. Your support much appreciated.
