### ISSUE TITLE
trackpad have lag and double tab not good 3finger for change desktop

### ISSUE THREAD

**Issue by Edwardwich** [VoodooSMBus/VoodooRMI#139]
**trackpad have lag and double tab not good 3finger for change desktop**
trackpad have lag and double tab not good 3finger for change desktop
this problem only on Mac OS Monterey

**To Reproduce**
voodooRMI.kext-v13.5
VoodooPS2Controller.kext-v2.2.7

**IORegistryExplorer**

[ioreg.zip](https://github.com/VoodooSMBus/VoodooRMI/files/7556957/ioreg.zip)

**Log**
log from Hackintool

[log .zip](https://github.com/VoodooSMBus/VoodooRMI/files/7556949/log.zip)

**Comment by 1Revenger1** [comment]
ACPIBatteryManager known to cause issues due to sleep delays in the _STA method for your batteries. Try using VirtualSMC

**Comment by Edwardwich** [comment]
Its my laptop git 
https://github.com/OpenIntelWireless/itlwm

**Comment by 1Revenger1** [comment]
Sorry, I don't really understand what you are saying. It sounds like possibly an issue with your BAT device not getting notifications when plugging/unplugging the device. I'd try with ACPIBatteryManager anyways just to see if the issue goes away. If it does, then you can spend more time making it work better.

**Comment by Edwardwich** [comment]
> Sorry, I don't really understand what you are saying. It sounds like possibly an issue with your BAT device not getting notifications when plugging/unplugging the device. I'd try with ACPIBatteryManager anyways just to see if the issue goes away. If it does, then you can spend more time making it work better.

plz see this picture 

laptop adapor 60w and show 300w:
![IMAGE 1400-08-27 12:48:29](https://user-images.githubusercontent.com/35195176/142386921-cf43af06-2bf0-416f-b481-bd63ee3cb616.jpg)

and after show using adapter :

![IMAGE 1400-08-27 12:53:51](https://user-images.githubusercontent.com/35195176/142387660-da2a1ac7-d360-44b7-b752-5c1957e6c84a.jpg)

![IMAGE 1400-08-27 12:48:22](https://user-images.githubusercontent.com/35195176/142387206-6b38b051-7f89-4e84-9bc2-11ebada00637.jpg)

and after back to charging : 

![IMAGE 1400-08-27 12:48:25](https://user-images.githubusercontent.com/35195176/142387461-60556bd7-5195-464b-a14c-4326939c9792.jpg)


![IMAGE 1400-08-27 12:48:35](https://user-images.githubusercontent.com/35195176/142387495-4373e386-4ec7-446d-a470-b34ca266dad7.jpg)

**Comment by 1Revenger1** [comment]
Oops, meant SMCBatteryManager in my previous post.

Does the lag go away when using SMCBatteryManager? Not worth trying to fix power adapter status if it doesn't fix the issue.

**Comment by Edwardwich** [comment]
> Oops, meant SMCBatteryManager in my previous post.
> 
> Does the lag go away when using SMCBatteryManager? Not worth trying to fix power adapter status if it doesn't fix the issue.

Trackpad work better 
But have some lag

This problem I have smc battery manger kext Is it non-fixable? 
Iuse hackintosh Forums in telegram but no one find for fix this problem
Can you help?
