### ISSUE TITLE
Thinkpad x280 Trackpoint deadzone/lowresolution

### ISSUE THREAD

**Issue by Polishapple** [VoodooSMBus/VoodooRMI#147]
Model: Lenovo ThinkPad x280
Issue: trackpoint deadzone too big

I'm having problem with trackpoint deadzone. I got it set for 1 - lowest value, but still when trying to move a cursor a little bit it's not registering the movement. It feels like trackpoint resolution is too low or deadzone value is too big. I don't have this issue when using clean voodoops2controller without voodooRMI

**Comment by 1Revenger1** [comment]
You can set the deadzone to zero to disable it. I just checked and it shouldn't cause any errors.
By default, VoodooRMI has 2:1 mode enabled for the trackpoint but I'm thinking that it isn't that great, so I may remove it in a future release. If you don't mind building yourself, you could try disabling it here: https://github.com/VoodooSMBus/VoodooRMI/blob/master/VoodooRMI/Functions/F03.cpp#L270
