### ISSUE TITLE
Doesn't build/load with VoodooSMBUS-master

### ISSUE THREAD

**Issue by benbender** [VoodooSMBus/VoodooRMI#15]
**Describe the bug**
I've tried to build VoodooRMI-master with VoodooSMBUS-master and can't get it to build/work. It works fine with the VoodooSMBus-build from the VodooRMBUS-release-zip.

Problem seems to be the missing VoodooSMBusDeviceNub:wakeupController()-method which is, according to the headers, available in the Release-zip and missing in VoodooSMBUS-master.

If I remove the call in VoodooRMBUS it builds, but VoodooRMBUS doesn't attach to VoodooSMBusDeviceNub.

(If this is expected at the current stage, a note in the readme would be fine!)

**To Reproduce**
1. Build VoodooSMBUS-master
2. Try to build VoodooRMBUS-master against VoodooSMBUS-master

**Log**
````
+++ b/VoodooRMI/Transports/RMISMBus.cpp
@@ -35,7 +35,7 @@ RMISMBus *RMISMBus::probe(IOService *provider, SInt32 *score)
         return NULL;
     }

-    device_nub->wakeupController();
+    // device_nub->wakeupController();
     device_nub->setSlaveDeviceFlags(I2C_CLIENT_HOST_NOTIFY);

     do {
````

**Comment by 1Revenger1** [comment]
There is a PR into VoodooSMBus with changes I have made - it is known that VoodooSMBus-master does not build this.
