### ISSUE TITLE
No trackpoint

### ISSUE THREAD

**Issue by Rohan200220** [VoodooSMBus/VoodooRMI#16]
Hey, I followed all the instructions and my trackpad and gestures are working but there is no trackpoint.

**Comment by 1Revenger1** [comment]
I need logs, and a picture of IORegistryExplorer would be appreciated.

Will open once more information is provided

**Comment by Rohan200220** [comment]
![Screenshot 2020-07-08 at 3 42 43 AM](https://user-images.githubusercontent.com/58611972/86849409-3ea43900-c0cd-11ea-9323-33a1ed801e00.png)

No result is coming when trying to obtain logs.

**Comment by Rohan200220** [comment]
Also I am using the latest version of VoodooRMI that was posted 2 hours ago.

**Comment by 1Revenger1** [comment]
Your IOReg suggests that there is no trackpoint. Can you boot linux and run `lsdev`? Send the output here

**Comment by Rohan200220** [comment]
I don’t have linux installed, only windows

**Comment by 1Revenger1** [comment]
Without a log or more info - there is nothing I can do.
You may try loading it manually within windows using `kextload -d VoodooSMBus.kext VoodooRMI.kext`
May have better luck getting a log from using `dmesg` as well

**Comment by Rohan200220** [comment]
Using dmesg gives me a lot of things, I just wrote sudo dmesg in terminal, Would that be helpful? Because I really want to use this trackpad kext as its gestures are working amazing

**Comment by 1Revenger1** [comment]
Sure, I guess you can give the entire dmesg log
`dmesg > ~/Desktop/Log.txt`

**Comment by Rohan200220** [comment]
[log.txt](https://github.com/VoodooSMBus/VoodooRMI/files/4893259/log.txt)
Here it is.

**Comment by 1Revenger1** [comment]
Hmm, it seems very truncated and incomplete. There's no useful info in it other than the fact that the trackpad is working.

**Comment by Rohan200220** [comment]
So what should i do now? Any other way of obtaining logs? Would the bootlog work that is obtained from clover configurator?

**Comment by 1Revenger1** [comment]
Can try loading it manually once within macOS using `sudo kextload`

**Comment by Rohan200220** [comment]
Its giving me this error- failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8).

**Comment by 1Revenger1** [comment]
When loading kexts:
SIP needs to at least be partially disabled to allow unsigned kexts to load
The kext needs to be owned by root (`sudo chown -R root:wheel VoodooRMI.kext`) - You may need to do the same thing with VoodooSMBus
Remember to load using `sudo kextload -d VoodooSMBus.kext VoodooRMI.kext`

**Comment by Rohan200220** [comment]
So I disabled SIP from recovery, and ran this command

log show --last 1h | grep -I voodoormi

And it is giving me some failing logs.
[logs.txt](https://github.com/VoodooSMBus/VoodooRMI/files/4893376/logs.txt)

And now My trackpad is not working and its not showing in System Preferences either.
Also I think I edited my device id Correctly in info.plist
![Screenshot 2020-07-09 at 3 02 44 AM](https://user-images.githubusercontent.com/58611972/86972866-40373500-c191-11ea-9695-6b6dfd8b1b4f.png)

**Comment by 1Revenger1** [comment]
Are VoodooSMBus.kext/VoodooRMI.kext under /Users/rohan/ ? Its saying that it can't find the kexts.
`Unable to determine realpath for /Users/rohan/VoodooRMI.kext - failing`
You need to be in the same folder as the kexts, or specify the path for them

**Comment by Rohan200220** [comment]
I also Tried this command-sudo kextload -d VoodooSMBus.kext VoodooRMI.kext
 but its giving me this

No kernel extensions specified; name kernel extension bundles
    following options, or use -bundle-id (-b).
usage: kextload [options] [--] [kext] ...

use kextload -help for an explanation of each option
