### ISSUE TITLE
SYNA32CB support

### ISSUE THREAD

**Issue by big-mak** [VoodooSMBus/VoodooRMI#171]
Didn't see SYNA32CB in the readme, would appreciate if support was added. Thanks

**Comment by 1Revenger1** [comment]
The trackpad likely works if it works in Linux, Have you tested VoodooRMI with this trackpad?

**Comment by big-mak** [comment]
I have tested it and I can't get it to work, boot gets stuck at messages like this: `ApplePS2ALPSGlidePoint: identify: not an ALPS device: Error getting E6 report`
I have tried with and without VoodooI2C and various combinations of the relevant sattelite kexts. Discussing this [here](https://forum.amd-osx.com/threads/nootedred-renoir-cezanne-apus-installing-on-ryzen-7-5825u-installer-freezes-at-12min-every-time.4555/page-2#post) and latest EFI attached 
[EFI.zip](https://github.com/VoodooSMBus/VoodooRMI/files/12012362/EFI.zip)

**Comment by 1Revenger1** [comment]
Are you able to boot into macOS at all even without VoodooI2C and VoodooRMI?
If you have an I2C trackpad, you should probably disable VoodooPS2Mouse and Trackpad.

**Comment by big-mak** [comment]
Used a VoodooI2C build from NootInc and it works now.
