### ISSUE TITLE
Support for 0x432f touchscreen by Raydium

### ISSUE THREAD

**Issue by Mifaxav** [VoodooSMBus/VoodooRMI#172]
**Describe the bug**
If the trackpad is not working, or behaving weirdly, you are expected to provide a Log.

Its just not working or im not doing it right... The touchpad is USB based btw

**To Reproduce**

N/A

**Expected behavior**

The touchscreen should work with gestures if im not mistaken

**Log**
The `log` command is not very good if you are trying to get logs from early boot. Generally it's better to add `msgbuf=1048576` to your boot args and use `sudo dmesg | grep -i vrmi > ~/Desktop/log.txt` once booted in. You will want to use the DEBUG version of the driver as it provides more logging info. If you attach a log using the RELEASE version, we may ask you to use the DEBUG version and redo the log. This will provides logs for VoodooRMI from when the device was booted up.

N/A

**Comment by 1Revenger1** [comment]
Does this use the RMI4 protocol?
This would be the first RMI4 touchscreen I've seen, maybe double check in Linux to see what it uses? Check for hid-rmi. If it says hid-multitouch, then you want VoodooI2CHID.

If this is USB, then like the I2C transport needs to be rewritten or a new HID transport is needed.
