### ISSUE TITLE
RMI_READ_DATA_REPORT_ID

### ISSUE THREAD

**Issue by bopv2** [VoodooSMBus/VoodooRMI#174]
**Describe the bug**
It disabled the trackpad?

**To Reproduce**
1. Happens randomly.

**Expected behavior**
Trackpad to work.

**Log**
VRMI - Error: Unable to read IRQ _<---- spammed_
VRMI - Error: RMII2C::TDP0 RMI_READ_DATA_REPORT_ID mismatch 0  _<---- spammed_
connect() - failed necp_set_socket_domain_attributesVRMI _<---- isnt spammed as much_

**Comment by 1Revenger1** [comment]
If you are still around, want to give this a shot?
https://github.com/VoodooSMBus/VoodooRMI/pull/193/commits/f63343c70fbe8212e68b029c89ba407390834256
