### ISSUE TITLE
Tap to click not working normally

### ISSUE THREAD

**Issue by xfwdrev** [VoodooSMBus/VoodooRMI#175]
Tap to click does work normally. Have to tap the touchpad a couple of times and tap hard to register the clicks.

Tap to click also doesn't work when tapping in the middle of the trackpad. It only works when tapping in bottom center of the touchpad. 

Gesture works normally detecting up to five fingers.

My touchpad is SYN1B7F running in polling mode.

**Comment by Hackashaq666** [comment]
Same here

**Comment by TotallyNotInUse** [comment]
I had the same problem, however I discovered that my trackpad (Thinkpad T15 Gen 1) should actually use VoodooI2C instead of VoodooRMI so I'm sharing this in hopes it helps to solve your problem.

**Comment by speedie1337** [comment]
Can confirm this issue. Works sometimes when waking from sleep.

**Comment by 1Revenger1** [comment]
I believe should be solved by https://github.com/VoodooSMBus/VoodooRMI/actions/runs/11307575354/artifacts/2048920273 and other commits to VoodooSMBus/VoodooRMI.
Let me know if it is not.
