### ISSUE TITLE
No support for SYNA2B3E

### ISSUE THREAD

**Issue by notAf7zz** [VoodooSMBus/VoodooRMI#176]
**Describe the bug**
Everytime I add VoodooRMI to my lenovov130-14ikb(81HQ) it never boots up and it requires VoodooRMI as it is a i2c Synaptics touchpad.I think its because SYNA2B3E is not included.Also,Whenever I add Voodooi2CHID(without VoodooRMI) it starts to work but no gestures

**To Reproduce**
Adding VoodooRMI.kext

**Expected behavior**
For the kext to work and enable gestures on my trackpad

**Log**
AppleStoreKey : 12143 : Operation Failed

**Comment by 1Revenger1** [comment]
If you are around still, does this version help?
https://github.com/VoodooSMBus/VoodooRMI/actions/runs/11443856445/artifacts/2083312274
