### ISSUE TITLE
No support for SYNA2BA6

### ISSUE THREAD

**Issue by kuguazhiwang** [VoodooSMBus/VoodooRMI#179]
Computer: Lenove yoya 14s R7 5800H  
macOS version: macOS sonoma 14.4
Open Core version: (latest as of posting)

Device Manager:
![image](https://github.com/VoodooSMBus/VoodooRMI/assets/18096433/a8a906c3-1a30-40bc-8538-dfd13c74b3b1)

Bug description:
When I use VoodooRMI (along with Voodoo I2C), in macOS recovery/installer/installed, it fails to work. The device manager hardware IDs are shown above. The kexts are all loaded successfully, checking the log.

I hope there are tutorials that can help us DIY or solve problems

**Comment by 1Revenger1** [comment]
Is this using the latest commit of VoodooI2C? The latest release of VoodooI2C does not include support for AMD I2C Controllers.

**Comment by kuguazhiwang** [comment]
https://github.com/VoodooI2C/VoodooI2C/pull/547#issuecomment-2076129321   
 and  add :NVRAM->boot-args  -vi2c-force-polling   
 can be useful ！
