### ISSUE TITLE
VoodooRMI 1.4 doesnt work on my XPS15

### ISSUE THREAD

**Issue by gujiangjiang** [VoodooSMBus/VoodooRMI#184]
![QQ_1728340732539](https://github.com/user-attachments/assets/0c37fc80-60ea-499f-adee-583cae7ddfcc)

Here are the kext list
The VoodooPS2 VoodooI2C VoodooRMI VoodooInput are all latest version.

Using VoodooRMI 1.3.5 the trackpad works perfectly bug when updated to 1.4.0 the trackpad not works now.
My touchpad is synaptic I2C trackpad.

**Comment by 1Revenger1** [comment]
Are you able to provide logs? Would you be willing to go through [here](https://dortania.github.io/builds/?product=VoodooRMI&viewall=true) as well and bisect commits from [4d61d8b](https://github.com/VoodooSMBus/VoodooRMI/commit/4d61d8b3d2b372278be394b682ab0a306ca1295b) to [fb93f3f](https://github.com/VoodooSMBus/VoodooRMI/commit/fb93f3f1b1d4285fca5f9e5b5db6a55979ef5ef3)?

**Comment by gujiangjiang** [comment]
> Are you able to provide logs? Would you be willing to go through [here](https://dortania.github.io/builds/?product=VoodooRMI&viewall=true) as well and bisect commits from [4d61d8b](https://github.com/VoodooSMBus/VoodooRMI/commit/4d61d8b3d2b372278be394b682ab0a306ca1295b) to [fb93f3f](https://github.com/VoodooSMBus/VoodooRMI/commit/fb93f3f1b1d4285fca5f9e5b5db6a55979ef5ef3)?您能提供日志吗？您是否愿意也浏览一下这里，并将 4d61d8b 到 fb93f3f 的提交一分为二？

I will try evey version from [4d61d8b](https://github.com/VoodooSMBus/VoodooRMI/commit/4d61d8b3d2b372278be394b682ab0a306ca1295b) to [fb93f3f](https://github.com/VoodooSMBus/VoodooRMI/commit/fb93f3f1b1d4285fca5f9e5b5db6a55979ef5ef3)

give me some time to get logs and feedback. thanks.

**Comment by gujiangjiang** [comment]
gujiangjiang@gujiangjiangdeMacBook-Pro-4 ~ % sudo dmesg | grep VRMI
gujiangjiang@gujiangjiangdeMacBook-Pro-4 ~ % 

no logs found.

**Comment by gujiangjiang** [comment]
@1Revenger1 
Here are the logs with VoodooPS2 2.3.5 + VoodooRMI 1.3.5 and works perfectly.

[    1.740905]: VRMI - Debug: RMII2C::TPDX probing
[    1.741777]: VRMI - Debug: RMII2C::TPDX Trying to set mode, attempt 0
[    1.742096]: VRMI - Debug: RMII2C::TPDX mode set
[    2.244926]: VRMI - Debug: Config TrackpointMultiplier loaded: a -> a
[    2.244931]: VRMI - Debug: Config TrackpointScrollMultiplierX loaded: a -> 1e
[    2.244935]: VRMI - Debug: Config TrackpointScrollMultiplierY loaded: a -> 1e
[    2.244938]: VRMI - Debug: Config TrackpointDeadzone loaded: 1 -> 1
[    2.244941]: VRMI - Debug: Config DisableWhileTypingTimeout loaded: 7d0 -> fa
[    2.244944]: VRMI - Debug: Config DisableWhileTrackpointTimeout loaded: 7d0 -> fa
[    2.244947]: VRMI - Debug: Config ForceTouchMinPressure loaded: 50 -> 5a
[    2.244950]: VRMI - Debug: Config ForceTouchType loaded: 1 -> 1
[    2.244952]: VRMI - Debug: Config MinYDiffThumbDetection loaded: c8 -> c8
[    2.244955]: VRMI - Debug: Config FingerMajorMinorDiffMax loaded: a -> a
[    2.244957]: VRMI - Debug: Config PalmRejectionWidth loaded: f -> a
[    2.244960]: VRMI - Debug: Config PalmRejectionHeight loaded: 50 -> 3c
[    2.244962]: VRMI - Debug: Config PalmRejectionTrackpointHeight loaded: 14 -> 14
[    2.244965]: VRMI - Debug: Updating Configuration
[    2.244974]: VRMI - Info: RMI Bus (DEBUG) Starting up!
[    2.246777]: VRMI - Debug: RMII2C::TPDX mode set
[    2.246796]: VRMI - Info: RMII2C::TPDX reset completed
[    2.246798]: VRMI - Error: Unable to reset
[    2.246800]: VRMI - Error: RMI initial reset failed! Continuing in spite of this
[    2.247404]: VRMI - Debug: rmi_probe_interrupts: Counting IRQs
[    2.267729]: VRMI - Debug: IRQ Count: 7
[    2.267806]: VRMI - Debug: rmi_init_functions: Creating functions
[    2.269554]: VRMI - Info: Initializing F34.
[    2.269558]: VRMI - Debug: Function F34 - IRQs: 1 CMD Base: 0 CTRL Base: 12 DATA Base: 0 QRY Base: 34 VER: 1
[    2.269562]: VRMI - Info: F34 not implemented
[    2.270268]: VRMI - Info: Initializing F01.
[    2.270271]: VRMI - Debug: Function F1 - IRQs: 1 CMD Base: 33 CTRL Base: 16 DATA Base: 4 QRY Base: 38 VER: 0
[    2.275590]: VRMI - Info: Found RMI4 device, manufacturer: Synaptics, product: TM3125-001, fw id: 1961136
[    2.278265]: VRMI - Info: Initializing F12.
[    2.278283]: VRMI - Debug: Function F12 - IRQs: 2 CMD Base: 0 CTRL Base: 22 DATA Base: 7 QRY Base: 67 VER: 0
[    2.281205]: VRMI - Debug: F12 - reg: 0 reg size: 1 subpackets: 1
[    2.281208]: VRMI - Debug: F12 - reg: 1 reg size: 1 subpackets: 1
[    2.281229]: VRMI - Debug: F12 - reg: 2 reg size: 3 subpackets: 2
[    2.281232]: VRMI - Debug: F12 - reg: 3 reg size: 31 subpackets: 12
[    2.281235]: VRMI - Debug: F12 - reg: 4 reg size: 1 subpackets: 1
[    2.281237]: VRMI - Debug: F12 - reg: 5 reg size: 5 subpackets: 2
[    2.281241]: VRMI - Debug: F12 - reg: 6 reg size: 25 subpackets: 11
[    2.281243]: VRMI - Debug: F12 - reg: 7 reg size: 1 subpackets: 1
[    2.281246]: VRMI - Debug: F12 - reg: 8 reg size: 3 subpackets: 2
[    2.281249]: VRMI - Debug: F12 - reg: 9 reg size: 10 subpackets: 5
[    2.281252]: VRMI - Debug: F12 - reg: 10 reg size: 1 subpackets: 1
[    2.281255]: VRMI - Debug: F12 - reg: 13 reg size: 1 subpackets: 1
[    2.283572]: VRMI - Debug: F12 - reg: 8 reg size: 10 subpackets: 3
[    2.283576]: VRMI - Debug: F12 - reg: 9 reg size: 15 subpackets: 3
[    2.283596]: VRMI - Debug: F12 - reg: 10 reg size: 17 subpackets: 3
[    2.283599]: VRMI - Debug: F12 - reg: 11 reg size: 15 subpackets: 4
[    2.283602]: VRMI - Debug: F12 - reg: 15 reg size: 7 subpackets: 3
[    2.283605]: VRMI - Debug: F12 - reg: 19 reg size: 67 subpackets: 5
[    2.283608]: VRMI - Debug: F12 - reg: 20 reg size: 1 subpackets: 1
[    2.283611]: VRMI - Debug: F12 - reg: 21 reg size: 2 subpackets: 1
[    2.283613]: VRMI - Debug: F12 - reg: 22 reg size: 1 subpackets: 1
[    2.283616]: VRMI - Debug: F12 - reg: 23 reg size: 2 subpackets: 2
[    2.283619]: VRMI - Debug: F12 - reg: 28 reg size: 1 subpackets: 1
[    2.285437]: VRMI - Debug: F12 - reg: 1 reg size: 40 subpackets: 5
[    2.285440]: VRMI - Debug: F12 - reg: 2 reg size: 1 subpackets: 1
[    2.285442]: VRMI - Debug: F12 - reg: 5 reg size: 15 subpackets: 5
[    2.285445]: VRMI - Debug: F12 - reg: 9 reg size: 10 subpackets: 5
[    2.285448]: VRMI - Debug: F12 - reg: 15 reg size: 1 subpackets: 1
[    2.285451]: VRMI - Debug: F12 - Data packet size: 0x43
[    2.286216]: VRMI - Debug: F12 - Number of fingers 5
[    2.287779]: VRMI - Info: Initializing F54.
[    2.287781]: VRMI - Debug: Function F54 - IRQs: 1 CMD Base: 301 CTRL Base: 269 DATA Base: 256 QRY Base: 302 VER: 0
[    2.287786]: VRMI - Info: F54 not implemented
[    2.289390]: VRMI - Info: Initializing F30.
[    2.289393]: VRMI - Debug: Function F30 - IRQs: 1 CMD Base: 512 CTRL Base: 513 DATA Base: 512 QRY Base: 519 VER: 0
[    2.290758]: VRMI - Debug: F30: Found Button 1 at 2
[    2.292336]: VRMI - Info: Initializing F55.
[    2.292339]: VRMI - Debug: Function F55 - IRQs: 1 CMD Base: 772 CTRL Base: 768 DATA Base: 768 QRY Base: 773 VER: 0
[    2.292343]: VRMI - Info: F55 not implemented
[    2.650530]: VRMI - Debug: RMII2C::TPDX powerState 1 : on
[   34.450908]: VRMI - Debug: F12 Packet
[   34.450923]: VRMI - Debug: Velocity: 0 0 Zone: 0
[   34.450928]: VRMI - Debug: Finger num: 0 (valid) (542, 497) [Z: 51 WX: 4 WY: 3 FingerType: 0 Pressure : 0 Button: 0]
[   34.458742]: VRMI - Debug: F12 Packet
[   34.458755]: VRMI - Debug: Finger num: 0 (valid) (573, 490) [Z: 52 WX: 4 WY: 3 FingerType: 2 Pressure : 0 Button: 0]
[   34.466586]: VRMI - Debug: F12 Packet
[   34.466619]: VRMI - Debug: Finger num: 0 (valid) (605, 479) [Z: 53 WX: 4 WY: 3 FingerType: 2 Pressure : 0 Button: 0]
[   34.474536]: VRMI - Debug: F12 Packet
[   34.474570]: VRMI - Debug: Finger num: 0 (valid) (633, 469) [Z: 53 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.482135]: VRMI - Debug: F12 Packet
[   34.482146]: VRMI - Debug: Finger num: 0 (valid) (660, 462) [Z: 54 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.489976]: VRMI - Debug: F12 Packet
[   34.490003]: VRMI - Debug: Finger num: 0 (valid) (689, 453) [Z: 54 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.497869]: VRMI - Debug: F12 Packet
[   34.497887]: VRMI - Debug: Finger num: 0 (valid) (713, 441) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.505504]: VRMI - Debug: F12 Packet
[   34.505530]: VRMI - Debug: Finger num: 0 (valid) (740, 428) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.513107]: VRMI - Debug: F12 Packet
[   34.513133]: VRMI - Debug: Finger num: 0 (valid) (763, 417) [Z: 55 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.521041]: VRMI - Debug: F12 Packet
[   34.521067]: VRMI - Debug: Finger num: 0 (valid) (788, 404) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.528758]: VRMI - Debug: F12 Packet
[   34.528784]: VRMI - Debug: Finger num: 0 (valid) (813, 385) [Z: 56 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.536389]: VRMI - Debug: F12 Packet
[   34.536408]: VRMI - Debug: Finger num: 0 (valid) (834, 373) [Z: 55 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.544126]: VRMI - Debug: F12 Packet
[   34.544139]: VRMI - Debug: Finger num: 0 (valid) (856, 361) [Z: 55 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.551647]: VRMI - Debug: F12 Packet
[   34.551698]: VRMI - Debug: Finger num: 0 (valid) (876, 345) [Z: 55 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.559612]: VRMI - Debug: F12 Packet
[   34.559639]: VRMI - Debug: Finger num: 0 (valid) (892, 332) [Z: 56 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.567203]: VRMI - Debug: F12 Packet
[   34.567217]: VRMI - Debug: Finger num: 0 (valid) (908, 322) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.574815]: VRMI - Debug: F12 Packet
[   34.574828]: VRMI - Debug: Finger num: 0 (valid) (921, 318) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.582466]: VRMI - Debug: F12 Packet
[   34.582474]: VRMI - Debug: Finger num: 0 (valid) (927, 312) [Z: 56 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.590072]: VRMI - Debug: F12 Packet
[   34.590088]: VRMI - Debug: Finger num: 0 (valid) (939, 300) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.597956]: VRMI - Debug: F12 Packet
[   34.598005]: VRMI - Debug: Finger num: 0 (valid) (942, 297) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.605799]: VRMI - Debug: F12 Packet
[   34.605811]: VRMI - Debug: Finger num: 0 (valid) (948, 291) [Z: 56 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.613745]: VRMI - Debug: F12 Packet
[   34.613760]: VRMI - Debug: Finger num: 0 (valid) (949, 288) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.621275]: VRMI - Debug: F12 Packet
[   34.621282]: VRMI - Debug: Finger num: 0 (valid) (949, 288) [Z: 56 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.629115]: VRMI - Debug: F12 Packet
[   34.629124]: VRMI - Debug: Finger num: 0 (valid) (949, 288) [Z: 56 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.636889]: VRMI - Debug: F12 Packet
[   34.636899]: VRMI - Debug: Finger num: 0 (valid) (943, 292) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.644705]: VRMI - Debug: F12 Packet
[   34.644714]: VRMI - Debug: Finger num: 0 (valid) (925, 309) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.652538]: VRMI - Debug: F12 Packet
[   34.652546]: VRMI - Debug: Finger num: 0 (valid) (904, 321) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.660355]: VRMI - Debug: F12 Packet
[   34.660364]: VRMI - Debug: Finger num: 0 (valid) (876, 335) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.668183]: VRMI - Debug: F12 Packet
[   34.668192]: VRMI - Debug: Finger num: 0 (valid) (849, 353) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.675959]: VRMI - Debug: F12 Packet
[   34.675968]: VRMI - Debug: Finger num: 0 (valid) (822, 366) [Z: 54 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.683772]: VRMI - Debug: F12 Packet
[   34.683780]: VRMI - Debug: Finger num: 0 (valid) (793, 378) [Z: 53 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.691507]: VRMI - Debug: F12 Packet
[   34.691516]: VRMI - Debug: Finger num: 0 (valid) (768, 389) [Z: 52 WX: 4 WY: 3 FingerType: 2 Pressure : 0 Button: 0]
[   34.699285]: VRMI - Debug: F12 Packet
[   34.699293]: VRMI - Debug: Finger num: 0 (valid) (743, 402) [Z: 52 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.706953]: VRMI - Debug: F12 Packet
[   34.706961]: VRMI - Debug: Finger num: 0 (valid) (718, 415) [Z: 51 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.714728]: VRMI - Debug: F12 Packet
[   34.714737]: VRMI - Debug: Finger num: 0 (valid) (699, 422) [Z: 51 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.722549]: VRMI - Debug: F12 Packet
[   34.722560]: VRMI - Debug: Finger num: 0 (valid) (687, 428) [Z: 52 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.730360]: VRMI - Debug: F12 Packet
[   34.730368]: VRMI - Debug: Finger num: 0 (valid) (680, 431) [Z: 53 WX: 4 WY: 3 FingerType: 2 Pressure : 0 Button: 0]
[   34.738130]: VRMI - Debug: F12 Packet
[   34.738139]: VRMI - Debug: Finger num: 0 (valid) (673, 433) [Z: 53 WX: 4 WY: 3 FingerType: 2 Pressure : 0 Button: 0]
[   34.745890]: VRMI - Debug: F12 Packet
[   34.745898]: VRMI - Debug: Finger num: 0 (valid) (670, 433) [Z: 53 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.753659]: VRMI - Debug: F12 Packet
[   34.753668]: VRMI - Debug: Finger num: 0 (valid) (667, 433) [Z: 54 WX: 4 WY: 3 FingerType: 2 Pressure : 0 Button: 0]
[   34.761408]: VRMI - Debug: F12 Packet
[   34.761416]: VRMI - Debug: Finger num: 0 (valid) (666, 433) [Z: 54 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.769325]: VRMI - Debug: F12 Packet
[   34.769349]: VRMI - Debug: Finger num: 0 (valid) (665, 432) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.776915]: VRMI - Debug: F12 Packet
[   34.776923]: VRMI - Debug: Finger num: 0 (valid) (664, 431) [Z: 55 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.784723]: VRMI - Debug: F12 Packet
[   34.784731]: VRMI - Debug: Finger num: 0 (valid) (664, 429) [Z: 56 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.792547]: VRMI - Debug: F12 Packet
[   34.792555]: VRMI - Debug: Finger num: 0 (valid) (664, 426) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.800379]: VRMI - Debug: F12 Packet
[   34.800387]: VRMI - Debug: Finger num: 0 (valid) (668, 420) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.808285]: VRMI - Debug: F12 Packet
[   34.808294]: VRMI - Debug: Finger num: 0 (valid) (671, 414) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.815823]: VRMI - Debug: F12 Packet
[   34.815832]: VRMI - Debug: Finger num: 0 (valid) (677, 405) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.823675]: VRMI - Debug: F12 Packet
[   34.823684]: VRMI - Debug: Finger num: 0 (valid) (684, 392) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.831512]: VRMI - Debug: F12 Packet
[   34.831520]: VRMI - Debug: Finger num: 0 (valid) (688, 380) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.839326]: VRMI - Debug: F12 Packet
[   34.839334]: VRMI - Debug: Finger num: 0 (valid) (690, 375) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.847173]: VRMI - Debug: F12 Packet
[   34.847182]: VRMI - Debug: Finger num: 0 (valid) (696, 366) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.855015]: VRMI - Debug: F12 Packet
[   34.855023]: VRMI - Debug: Finger num: 0 (valid) (699, 355) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.862941]: VRMI - Debug: F12 Packet
[   34.862964]: VRMI - Debug: Finger num: 0 (valid) (700, 350) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.870668]: VRMI - Debug: F12 Packet
[   34.870677]: VRMI - Debug: Finger num: 0 (valid) (702, 344) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.878543]: VRMI - Debug: F12 Packet
[   34.878552]: VRMI - Debug: Finger num: 0 (valid) (702, 341) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.886103]: VRMI - Debug: F12 Packet
[   34.886109]: VRMI - Debug: Finger num: 0 (valid) (702, 338) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.893937]: VRMI - Debug: F12 Packet
[   34.893944]: VRMI - Debug: Finger num: 0 (valid) (701, 336) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.901853]: VRMI - Debug: F12 Packet
[   34.901883]: VRMI - Debug: Finger num: 0 (valid) (699, 334) [Z: 58 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.909405]: VRMI - Debug: F12 Packet
[   34.909414]: VRMI - Debug: Finger num: 0 (valid) (698, 332) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.917209]: VRMI - Debug: F12 Packet
[   34.917217]: VRMI - Debug: Finger num: 0 (valid) (696, 331) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.925034]: VRMI - Debug: F12 Packet
[   34.925042]: VRMI - Debug: Finger num: 0 (valid) (693, 329) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.932909]: VRMI - Debug: F12 Packet
[   34.932917]: VRMI - Debug: Finger num: 0 (valid) (691, 327) [Z: 57 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.940490]: VRMI - Debug: F12 Packet
[   34.940506]: VRMI - Debug: Finger num: 0 (valid) (688, 325) [Z: 55 WX: 5 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.948244]: VRMI - Debug: F12 Packet
[   34.948251]: VRMI - Debug: Finger num: 0 (valid) (687, 324) [Z: 52 WX: 4 WY: 4 FingerType: 2 Pressure : 0 Button: 0]
[   34.955123]: VRMI - Debug: F12 Packet

**Comment by 1Revenger1** [comment]
Hrmm oh I see what might be the issue.
Give this a shot - I forgot to set a ready bit in the I2C driver.
[VoodooRMI-1.4.1-DEBUG.zip](https://github.com/user-attachments/files/17293667/VoodooRMI-1.4.1-DEBUG.zip)
