### ISSUE TITLE
Touchpad dragging

### ISSUE THREAD

**Issue by marcolp98** [VoodooSMBus/VoodooRMI#20]
Hi! i'm using your driver and everything is working fine, but for some reason i can't use the touchpad to drag windows or select text.

**Comment by 1Revenger1** [comment]
How are you trying to drag?
macOS doesn't have double tap to drag enabled by default - so you have to enable it, or use a button.

**Comment by marcolp98** [comment]
Woooops, i forgot to enable dragging in settings, my bad

btw thank you and who is working on this, it's just a pre-release and everything is working perfectly.

**Comment by 1Revenger1** [comment]
Yep - main thing that's holding it from a 1.0 release are some couple outstanding panics that happen sometimes for a small subset of people, and the building system. Though, I think both are resolved now, or close to it.
