### ISSUE TITLE
Make Trackpoint Scroll feels smooth

### ISSUE THREAD

**Issue by SukkaW** [VoodooSMBus/VoodooRMI#22]
Currently Trackpoint scroll (with middle button) feels like mouse wheel: things scroll line by line.

Is it possible to make trackpoint scroll in a smooth way (like two fingers gesture on touchpad)?

**Comment by 1Revenger1** [comment]
I'm not entirely sure how to do that unfortunately. Would be nice to have though. An interim solution could be to use smoothScroll https://www.smoothscroll.net/mac/

**Comment by SukkaW** [comment]
@1Revenger1 Well, VoodooPS2 supports smooth scroll. I am not sure whether it is a feature of PS2 protocol or not.

**Comment by 1Revenger1** [comment]
It isn't a feature of PS2. The trackstick data reported is the same between the two buses.

I took a quick looks and found these properties, so I can take a look in a bit
https://github.com/acidanthera/VoodooPS2/blob/master/VoodooPS2Trackpad/VoodooPS2SynapticsTouchPad.cpp#L528

**Comment by gimdh** [comment]
https://github.com/VoodooSMBus/VoodooTrackpoint/pull/6
Last PR works fine with mine.

**Comment by SukkaW** [comment]
> [VoodooSMBus/VoodooTrackpoint#6](https://github.com/VoodooSMBus/VoodooTrackpoint/pull/6)
> Last PR works fine with mine.

I will have a test of your branch to see if it works.

**Comment by SukkaW** [comment]
> [VoodooSMBus/VoodooTrackpoint#6](https://github.com/VoodooSMBus/VoodooTrackpoint/pull/6)
> Last PR works fine with mine.

@gimdh I have a custom build and it works. And https://github.com/VoodooSMBus/VoodooRMI/issues/13 has been solved as well (The trackstick speed back to normal instead of too fast).

**Comment by gimdh** [comment]
I suspect high mouse scroll sensitivity in macOS was causing #13. Scroll is too slow for me, too, so we might revert patch done for #13.

**Comment by 1Revenger1** [comment]
I'll need to try it personally at some point, currently messing with Big Sur.

Cool that it fixed quite a bit though. I'll check out the sensitivity when I take a look at it. I don't see much point in decreasing the denominator (currently 20) but we could increase the default value maybe.

**Comment by 1Revenger1** [comment]
Haha, ok I might lower the denominator. I've currently got the multiplier at 40 (40/20 = 2x multiplier) and it's still pretty slow. This otherwise is smoother.

**Comment by gimdh** [comment]
I have just found out Trackpoint scroll is not smooth in terminal. Maybe something more should be done.

**Comment by 1Revenger1** [comment]
Afaik it isn't smooth even with a trackpad. 
Terminal isn't like other programs - it has rows and columns it adheres to afaik. I can test tomorrow but iirc trackpad and trackpoint behaved basically the same.

**Comment by SukkaW** [comment]
> Afaik it isn't smooth even with a trackpad.

Confirmed.

> I have just found out Trackpoint scroll is not smooth in terminal. Maybe something more should be done.

It should be considered as the desired behavior.

**Comment by gimdh** [comment]
I compared magic trackpad 2 with trackpoint and thought MT2 to be much more smoother than trackpoint but yes, Macbook Air behaves same, and touchpad uses MT2 simulation via VoodooInput so they should be identical. My bad.

I think faster polling rate might made difference.

**Comment by 1Revenger1** [comment]
Hmm, could be polling rate. My trackpoint doesn't react to the polling rate command so it could be pretty far off. Wouldn't mind if someone compared different rates vs power consumption so we could choose the optimal one

**Comment by gimdh** [comment]
@1Revenger1  It was way more simple problem. With Trackpoint scroll, multiple lines scroll at a time. However, with touchpad, only a single line scrolls at a time, but much more frequently. That's why I thought touchpad is smoother.
Skipping multiple lines at a time is generally bad for locating line, so I hope this to be fixed if possible. I wonder VoodooPS2 is any better.
