### ISSUE TITLE
T450s Big Sur can't load the VoodooRMI.kext or VoodooSMBus.kext

### ISSUE THREAD

**Issue by findyy99** [VoodooSMBus/VoodooRMI#23]
-  when I didi what the readme said, I still can't make the trackpad of T450s work. When I use the kextstat, I found that the kext wasn't loaded. 

-  I have use the debug kext, the boot log has nothing about voodoo, so the txt file is bank.

-  this is the kext.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/26852735/87264922-dfdb2700-c4f3-11ea-9ce8-1d018ca02074.png">

-  this is the config.plist.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/26852735/87264968-00a37c80-c4f4-11ea-9083-5f3284baaf12.png">

- the txt generated has nothing.
<img width="271" alt="image" src="https://user-images.githubusercontent.com/26852735/87265069-51b37080-c4f4-11ea-8740-356e4e80bdfd.png">

- should I disable SIP or do something to make the kext loaded ?

**Comment by 1Revenger1** [comment]
What Bootloader?
If it's OpenCore, are there any logs from opencore?
Kernel Collection or Prelinked Kernel?
Where is the kext? Is it injected or under Library/Extensions or other place?

I've tested it with Big Sur using Prelinked Kernel and it 100% worked. I'm not planning on testing more though with Big Sur.

**Comment by findyy99** [comment]
@1Revenger1 

- sorry, It's OpenCore. version 0.6.0

- I will upload the OpenCore log later

-  Prelinked Kernel

- The kext is in EFI/OC/kext

**Comment by findyy99** [comment]
This is the OpenCore log!
[opencore-2020-07-13-031013.txt](https://github.com/VoodooSMBus/VoodooRMI/files/4910413/opencore-2020-07-13-031013.txt)

**Comment by 1Revenger1** [comment]
Does it work under Catalina?
I'd also check IORegistryExplorer and make sure something isn't attached to SBUS other than VoodooSMBus

**Comment by findyy99** [comment]
@1Revenger1 I will try to boot my Catalina on my USB drive, and give a feedback later! Thank you!

**Comment by findyy99** [comment]
@1Revenger1 Sorry, it seems my problem. Catalina still doesn't work. Can you please help me with my EFI? 
[OC.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4910583/OC.zip)

**Comment by 1Revenger1** [comment]
Again, check SBUS under IORegistryExplorer

**Comment by findyy99** [comment]
- unfortunately, I think there is nothing about SBUS.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/26852735/87274176-b5966300-c50d-11ea-84ca-628cc88b40e1.png">

**Comment by 1Revenger1** [comment]
It may be a different name, should start with S though. Basically are looking for the SMBus PCI device. Basically you want to make sure VoodooSMBus is attached, not AppleSMBusPCI

**Comment by findyy99** [comment]
- I don't know why the AppleSMBusPCI.kext was loaded. So the  VoodooSMBus is not attached.
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/26852735/87274662-df9c5500-c50e-11ea-90d0-0e598b0477b2.png">

**Comment by 1Revenger1** [comment]
Hmm, so we haven't had anyone test this yet - my system doesn't need it. But can you try adding the two lines shown below under VoodooSMBus.kext/Contents/Info.plist? Should be done actually as below, right before the end of the plist

https://github.com/VoodooSMBus/VoodooSMBus/pull/41/files

**Comment by findyy99** [comment]
@1Revenger1 Anyway, Thank you so much, I will have a try! 👍

**Comment by 1Revenger1** [comment]
Yep. If you don't mind, can you send a DSDT as well? The above link should fix it, but I'm curious. AppleSMBusPCI will load on apple devices and is another kext for the i801 SMBus chip found on Intel chipsets. On some systems, it'll attach I'm guessing because some properties exist in ACPI that I'd like to double check. The above link is a much cleaner solution then any ACPI solution though.

**Comment by findyy99** [comment]
Sure! And I have tried add the above two lines to the plist. Doesn't work, this is the DSDT I am using. I really appreciate you taking the time to help me！
[DSDT.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4910890/DSDT.zip)

**Comment by 1Revenger1** [comment]
Were the two lines added right before
```
</dict>
</plist>
```
At the very end of the file?

And thanks for the DSDT, I'll take a look tomorrow. You don't have an SSDT for SBUS/MCHC also right? That would cause this as well

**Comment by findyy99** [comment]
- I add it to the end of` VoodooSMBus.kext/Contents/Info.plist`.Just like this

<img width="363" alt="image" src="https://user-images.githubusercontent.com/26852735/87276651-5e938c80-c513-11ea-98c0-8d1578508c94.png">

- No, I did have the `SSDT-MCHC.aml and SSDT-SMBU.aml`. This is the log of APCI.
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/26852735/87276925-e4afd300-c513-11ea-90fe-e03c5eafe73d.png">

**Comment by findyy99** [comment]
I have found the SMBU in the IORegistryExplorer. But not VoodooSMBus, It's AppleSMBusPCI.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/26852735/87278242-8f28f580-c516-11ea-832b-d2c8e0802d54.png">

**Comment by 1Revenger1** [comment]
Oh, this laptop is from like 2015. Likely needed the edit above, but you now also need to add the device id to the Info.plist. there should be instructions for adding device id in the README under the dev branch (not master!) in the VoodooSMBus repo.

**Comment by findyy99** [comment]
Sorry, I just realized maybe I should go to VoodooSMBus repository looking for some information. Thank you!😄😄👍👍👍

**Comment by findyy99** [comment]
amazing！I add my own device-id and vendor-id everything works fine!  Thank you again! 👍👍

**Comment by gimdh** [comment]
Can you check if VoodooInput kext is loaded properly? If you have Trackpoint, but no touchpad, then it is likely that VoodooInput not loading is the issue.

**Comment by findyy99** [comment]
@gimdh Thanks! I figure out it. The Voodooinput has been loaded. Just because my  
Acpibatterymanager or SMCBattery is not loaded. By the way, it works good on ThinkPad T450S!

**Comment by 1Revenger1** [comment]
Cool! Do you mind adding the device Id in a PR maybe for VoodooSMBus? If you can't figure it out, I can put a PR in for you.

**Comment by findyy99** [comment]
Sorry , I am not familiar with how to use Github,  Maybe you can put a PR!
