### ISSUE TITLE
0.5 release doesn't work on my TP-t480s  , but 0.4 works！！

### ISSUE THREAD

**Issue by eric2877** [VoodooSMBus/VoodooRMI#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Log**
Run `log show --last boot | grep -i voodoo > ~/Desktop/RMILog.txt` when using the DEBUG version of the driver. If you attach a log using the RELEASE version, we may ask you to use the DEBUG version and redo the log. This will provides logs for VoodooRMI from when the device was booted up.

**Comment by 1Revenger1** [comment]
Please provide the data as outlined in the issue template, as well as provide a screenshot from Ioregistryexplorer.
