### ISSUE TITLE
Ivy Bridge and older SMBus Devices do not respond

### ISSUE THREAD

**Issue by LocTran016** [VoodooSMBus/VoodooRMI#33]
Excuse me. Can you help me with this, please. I'm using **OpenCore 0.5.9** DEBUG for my Ivy Bridge laptop. Although I’ve tried to used the [VoodooRMI.kext, VoodooSMBus.kext](https://github.com/VoodooSMBus/VoodooRMI) but my synaptic trackpad didn’t work (Even I’ve tried disable VoodooPS2Mouse,Trackpad and then VoodooInput inside VoodooPS2 as wel, it can’t movel). I had used the troubleshoot page, too. As you see, there aren’t any SMBus-related SSDT and I’ve modified the VoodooSMBus.kext, too. Here is my EFI as well if you want. Thanks a lot for reading my message.
P/S: I also tried to add these patch from here: https://github.com/leo-labs/macOS-ThinkPad-T480s/blob/master/EFI/CLOVER/config.example.plist#L500-L535 but my mouse still can’t move
[EFI.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4989772/EFI.zip)
![2020-07-28_163221](https://user-images.githubusercontent.com/64778285/88695134-ac231280-d12b-11ea-8af1-0d74d96cc684.png)
## Edit
My laptop is a **Ivy Bridge**:
DELL INSPIRON 3421:
Core i5 3337U-HD4000
7 Series/C216 Chipset Family SMBus Controller
PS2SmartTouchpad.kext and Rehabman VoodooPS2.kext work with some 2 fingers feature (exclude zoom in, out,...)
## Update for version 1.0.1 by @LocTran016 
I don't know if this is a bug or may be that kind of thing but when I inject VoodooSMBus.kext and VoodooRMI.kext (involves the plug-in as well) but I can't do anything in my laptop (include moving the mouse and shut down) because my laptop just keep loading with a rainbow circle, I haven't had the ability to click on the apple icon for shutting down, too. It just keep loading for very long time so I did force turn off my laptop. I don't know if this is a bug in my laptop only or with some other laptops, too. What do you think about this, then. @1Revenger1 (The 1.0.0 has the same problem like this)
P/S: This hadn't occurred before I inject the kext through **OpenCore**  
# Update regarding to VoodooPS2
I have just found a interesting link about VoodooPS2 (don't know if your kexts have the same issues): [here](https://github.com/acidanthera/bugtracker/issues/890). I don't know if you can take a look at that link. I've used the [SSDT-Enable_DynamicEWMode.dsl](https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-Enable_DynamicEWMode.dsl) to fix my trackpad with the VoodooPS2 grabbed from acidanthera. It work quite good with force touch but physic buttons don't work. Thanks for reading my message, then (*If this is off-topic, just leave a comment and I will delete the update as soon as possibe*)

**Comment by 1Revenger1** [comment]
What bootloader? If it's OC, make sure that the order of kext loading is VoodooSMBus.kext, then VoodooRMI.kext, then finally RMISMBus.kext. Make sure that VoodooInput from RMI is being injected as well.
If that doesn't work, can you show what your SMBus looks like in IORegistryExplorer, and get the output from `kextstat` in terminal.

**Comment by LocTran016** [comment]
@1Revenger1 Maybe the issues is because ProperTree put them in wrong order. One more thing before trying your advice, can RMISMBus.kext be after Whatevergreen like this
![image](https://user-images.githubusercontent.com/64778285/88734491-430ac180-d162-11ea-9dbe-7655724a5ebf.png)

**Comment by 1Revenger1** [comment]
Yeah that's fine. The main important thing is that VoodooRMI and VoodooSMBus are before RMISMBus. Doesn't really matter what the order is between the two or if anything is before it/mixed in.

**Comment by LocTran016** [comment]
Well, Although I've set everything like what you say, it can't work, ask for what my SMBus looks like in IORegistryExplorer, and get the output from kextstat in terminal, I'll try to get them to you as soon as possible because I don't have any usb mouse and I can't use my built-in mouse so sorry a lot for that. I'll try to send them to you soon.
P/S: Here is my SMBUS hardward ID if you want:
![image](https://user-images.githubusercontent.com/64778285/88756027-a3aef400-d18c-11ea-9073-823d54922b66.png)
[EFI.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4992517/EFI.zip)

**Comment by LocTran016** [comment]
@1Revenger1 ,By the way, my bootloader is OpenCore and I don't know why but if I use the VoodooPS2.kext from Acidanthera my mouse won't work but if i use Rehabman's VoodooPS2 from here: https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller, my trackpad can work with 1 finger and some 2 fingers features (not all of them, scrolling is OK but I can zoom in/out). And here is my full specs by AIDA64 Engineer (a *.txt and *htm in the zip)
[Report.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4992654/Report.zip)
[Report.txt](https://github.com/VoodooSMBus/VoodooRMI/files/4992638/Report.txt)

**Comment by LocTran016** [comment]
For the others things I will try my best for them

**Comment by 1Revenger1** [comment]
I haven't gotten this to run succesfully on any Ivy Bridge laptops - I'm not entirely sure why. It may be a different version of RMI? Not entirely sure on that, especially since RMI4 goes back to around ~2012. You may have better luck loading it in manually once within the OS just using the keyboard.

```
sudo chown -R root:wheel *.kext
sudo kextutil -vvvv -d VoodooSMBus.kext -d VoodooRMI.kext VoodooRMI.kext/Contents/PlugIns/VoodooSMBus.kext
```

Then getting a log by doing

```
log show --last boot | grep -i voodoo > ~/Desktop/log.txt
```

**Comment by LocTran016** [comment]
Do I need to change -d VoodooSMBus.kext -d VoodooRMI.kext VoodooRMI.kext/Contents/PlugIns/VoodooSMBus.kext to my kext direction (by dragging the kext inside the terminal) or just copy and paste your code into the terminal, then. Thanks

**Comment by 1Revenger1** [comment]
The paths need to be accurate, if you are in the same directory as them then the above command should work. But if you aren't, then yes you need to make sure the path is correct to them all.

**Comment by LocTran016** [comment]
There is a problem that you don't have VoodooRMI.kext/Contents/PlugIns/VoodooSMBus.kext so I think that I should change it into this:
sudo chown -R root:wheel *.kext
sudo kextutil -vvvv -d VoodooSMBus.kext -d VoodooRMI.kext VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext

**Comment by LocTran016** [comment]
@1Revenger1 Well, I've tried both but couldn't work. Anyway, all the necessary file is here, sorry if is there anything is miss, just tell me and I'll give it to you.
[Fixing trackpad.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4995789/Fixing.trackpad.zip)

**Comment by gimdh** [comment]
https://www.rockbox.org/wiki/pub/Main/SansaFuzePlus/Synaptics_RMI3_Specification.pdf

I guess older touchpads with RMI3 use F10.

**Comment by gimdh** [comment]
@LocTran016 You have to cd into the downloaded and unzipped VoodooRMI folder. Also, make sure to use Debug kext for detailed log information.

**Comment by 1Revenger1** [comment]
It may be that it is RMI3, I haven't seen any way to detect which RMI version it is. It does look programmed very similarly to RMI4 though.

**Comment by LocTran016** [comment]
@gimdh Well, I've run like this: 
cd ~/Downloads/VoodooRMI-1.0-Debug
sudo chown -R root:wheel *.kext
sudo kextutil -vvvv -d VoodooSMBus.kext -d VoodooRMI.kext VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext
And this is what it shown in the terminal (the log is empty)
[Newest.zip](https://github.com/VoodooSMBus/VoodooRMI/files/4996143/Newest.zip)

**Comment by LocTran016** [comment]
I'm using catalina, do you think I need to mount the System in Read-Write

**Comment by LocTran016** [comment]
SIP is disabled

**Comment by gimdh** [comment]
Log should be located under Downloaded kext folder.
However, it seems you need to remove kext from OC bootloader first. (Just delete two Kext files.)
You can load kext after boot, and in this way you can test kext without reboot.

BTW, you may want to edit post for minor extra informations rather than posting new comment, as issue board is somewhat different from chat.

**Comment by 1Revenger1** [comment]
So, what I've noticed is that testing with another person is that on Ivy Bridge, when we ask for the SMBus version, it gets stuck and doesn't get any sort of response, so no attempts are logged to try and get the version. It may be that some sort of timeout may be needed.

**Comment by Rohan200220** [comment]
I am also on an ivy bridge laptop, Inspiron 14z 5423 and my trackpoint is also not working properly. I edited the VoodooSMBus info.plist file and entered my vender id and device id. All the gestures are working but the trackpoint is very laggy. Btw I am using Clover.

**Comment by LocTran016** [comment]
@Rohan200220 , I've tried that but didn't work, though

**Comment by Rohan200220** [comment]
@LocTran016 Sometimes it works for me, sometimes it doesn't. When I restart my laptop the trackpad doesn't even respond.

**Comment by 1Revenger1** [comment]
Does someone mind testing out these new versions of VoodooRMI and VoodooSMBus?
https://files.gitter.im/5e938b02d73408ce4fe02f4f/H2AL/VoodooRMI.kext.zip
https://files.gitter.im/5e938b02d73408ce4fe02f4f/66yp/VoodooSMBus.kext.zip

If you are injecting these kexts rather than loading it manually within macOS, better way to get logs it to add `msgbuf=1048576` to your boot args, and use `sudo dmesg` to get logs, as `log show --last boot` is pretty atrocious for early boot logs.

**Comment by Rohan200220** [comment]
My trackpad is still not responding with the above kexts, and I am using clover

**Comment by 1Revenger1** [comment]
I can't do anything without logs. Please reread my last message.

**Comment by Rohan200220** [comment]
[Log.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5139332/Log.txt)

Sorry, here it is

**Comment by 1Revenger1** [comment]
I'd double check which VoodooSMBus kext your using. It looks like it's trying to probe for an Elans trackpad, when all of the Elans stuff should've been taken out in the above VoodooSMBus download.

**Comment by Rohan200220** [comment]
I used voodoosmbus from the above link, and how to take out elen stuff from voodoosmbus?

**Comment by 1Revenger1** [comment]
There isn't any Elans stuff in the above link. If you check the Info.plist for the kext you have injected, it should be version `3.0`, and not have any Elans stuff within it. Additionally, should have a place to put different addresses.
This is currently what I see
![image](https://user-images.githubusercontent.com/13190749/91508587-c7994e80-e88c-11ea-9e42-bc88c24daf40.png)

**Comment by Rohan200220** [comment]
Um, sorry for being a noob :p, but what do i have to do?

**Comment by 1Revenger1** [comment]
Double check that you have the right Kext. Make sure that you don't have VoodooSMBus in kextcache, Library/Extensions, or System/Library/Extensions. If that all looks alright, double check that the Info.plist says it's version 3.0. You can find it by right clicking the kext in macOS and pressing "Show Package Contents". If your on windows, the kext already appears a folder so just look in there.

**Comment by Rohan200220** [comment]
I don't have VoodooSMBus in S/L/E or in L/E, where is kextcache location?
![Screenshot 2020-08-28 at 6 24 00 AM](https://user-images.githubusercontent.com/58611972/91509245-4f1ba780-e8f7-11ea-9ac6-c60b3997c75b.png)

It says version 3.0

**Comment by 1Revenger1** [comment]
Double check for duplicates I guess - the kext cache isn't stored in a place you can mess with. Easiest way I guess to be sure it's gone is to invalidate it using `sudo kextcache -i /`

**Comment by Rohan200220** [comment]
> sudo kextcache -i /. It'll complain about kexts that shouldn't be in L/E or S/L/E as well.

just got this-
KernelCache ID: C13F4697AEBE1E8A99946DD865E9237F

**Comment by Rohan200220** [comment]
I never installed any kexts in L/E or in S/L/E so I know no wrong kexts would be there. I just placed them in my EFI folder

**Comment by 1Revenger1** [comment]
Hmm, I guess you could try getting a log again

**Comment by LocTran016** [comment]
With the newest version of VoodooRMI and VoodooSMBus, the freezing is fixed as you said before but through System Preference, it doesn't detect my trackpad as a trackpad (I can't even move my mouse so I have to use a USB mouse). I still using the same laptop. I will update the EFI as soon as possible
Here is my log:
[Terminal Saved Output.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5141537/Terminal.Saved.Output.txt)

**Comment by 1Revenger1** [comment]
Your log doesn't show VoodooSMBus loading at all. Are you sure something else isn't attaching to SBUS like Apple's own SMBus kext?

**Comment by 1Revenger1** [comment]
What does IORegistryExplorer show? I didn't see any traces of VoodooSMBus in the logs.

**Comment by 1Revenger1** [comment]
Can you please post new responses rather than editing the one messages? I don't get notifications.

It shows VoodooSMBusIntelLpssI2C as attaching to `SBUS`, make sure you add the device ID to VoodooSMBus, not VoodooSMBusIntelLpssI2C.

**Comment by LocTran016** [comment]
As you have already said before, the freezing is fixed but I can't use my mouse (I don't have the ability to move the built-in mouse). Here is everything my config.plist, the kext and terminal log as well as the ioreg file. Through the terminal (`sudo dmesg`), there are some RMI configuration and the kexts are loaded as well

![image](https://user-images.githubusercontent.com/64778285/91713013-20315a00-ebb3-11ea-88d1-878091f6d0aa.png)


![image](https://user-images.githubusercontent.com/64778285/91712887-dea0af00-ebb2-11ea-91a9-280d7ab20e3e.png)

![image](https://user-images.githubusercontent.com/64778285/91712543-2115bc00-ebb2-11ea-9603-1a9096433fcf.png)

[Troubleshooting.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5149878/Troubleshooting.zip)

**Comment by proektus123** [comment]
I have tested it on my elitebook  9470m 
VoodooSMBus .kext and VoodooRMI.kext does not loads..  no info in kextstat. I have place these kexts in opencore kexts folder.

**Comment by LocTran016** [comment]
> I have tested it on my elitebook 9470m
> VoodooSMBus .kext and VoodooRMI.kext does not loads.. no info in kextstat. I have place these kexts in opencore kexts folder.

You should update (editing the comment) your specs. Did you try to clean snap shot, check that no VoodooPS2 mouse and trackpad in the config.plist, add the device id and vendor id (in SMBus troubleshooting)?

**Comment by 1Revenger1** [comment]
Hmm, that's weird that it doesn't respond.

Oh, that's weird - VoodooRMI is trying to boot up before rooting occurs? I wonder if it's booting up early or if it's inaccurate logging. It may be worth testing to see if delaying when VoodooRMI starts booting up would help. Easiest way is probably just loading it manually from within macOS to see if anything changes. If you can test this, csrutil needs to allow unsigned kexts to load. Assuming VoodooSMBus, VoodooRMI are in the same folder, you can run `sudo kextutil -vvvv -d VoodooSMBus.kext -d VoodooRMI.kext VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext`. The kexts do need to be owned by root (and I wouldn't recommend modifying the kexts in OC/Kexts), which you can make happen by running `sudo chown -R root:wheel *.kext` (this will make every kext in that directory be owned by Root)

**Comment by LocTran016** [comment]
I don't know if this may help:
I'm using this [Touchpad Driver](https://www.dell.com/support/home/en-vn/drivers/driversdetails?driverid=9nnk9&oscode=wt64a&productcode=inspiron-14-3421) for my Dell Insiron 3421 (OS: Window 10 LTSB 2016), and it seem like a lot of laptops sharing the same driver with mine, even the XPS 12 9Q33 which is using the 4th gen intel cpu. I don't have the enough knowledge to be sure that using the same driver mean the same device but I don't know if could take a look at this. Hope this will help you in some way

**Comment by 1Revenger1** [comment]
[VoodooRMI.kext 2.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5158267/VoodooRMI.kext.2.zip)
This tries to read Address 0x200, which should give the major/minor RMI version if it's an RMI3 device. Do you mind trying this version? It has no other modifications from master.

**Comment by LocTran016** [comment]
The mouse doesn't work, I have tried the lastest VoodooRMI.kext but didn't help (I still keep the same VoodooSMBus)
[Troubleshooting.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5159690/Troubleshooting.zip)

**Comment by 1Revenger1** [comment]
This should properly probe for RMI3 (Switches to Page 0x02 and probes address 0x00)
I also fixed the mapping table possibly not being zeroed at within RMISMBus, but I doubt that was the issue plaguing you.

I'm not expecting this to work for you, but it should hopefully give more helpful debug info
[VoodooRMI.kext 4.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5164950/VoodooRMI.kext.4.zip)

**Comment by LocTran016** [comment]
With the latest version of VoodooRMI.kext (I haven't change the VoodooSMBus.kext), my trackpad work perfectly, the launchpad work reliably although there is a small problem that when I first try to click, I have to  tap with one finger twice but from the second time, it work reliably (this also apply to other gestures as well)
[Troubleshooting.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5165766/Troubleshooting.zip)

**Comment by 1Revenger1** [comment]
Huh. So maybe it was not zeroing the mapping table out at boot. I'll upload the changes later after I've taken a look at the logs. Thanks for testing.

On Monday I'll push out a new release with a release binary

@Rohan200220 any luck getting this to work on your trackpad?

**Comment by LocTran016** [comment]
Do you think that I should try the VoodooSMBus as well because the trackpad work perfectly?

**Comment by 1Revenger1** [comment]
Na, functionality doesn't change at all

**Comment by 1Revenger1** [comment]
Oh, have you testing this over a few boots to make sure that we weren't being lucky for some reason?

**Comment by LocTran016** [comment]
No, I haven't done that yet

**Comment by LocTran016** [comment]
I have tried to load the SSDT-SBUS-MCHC (follow dortania guide) and the trackpad doesn't work at all so I delete that SSDT, enable 2 patch to prevent apple smbus kext attach to SMBUS controller (in VoodooSMBus instruction) as well as reset NVRAM but it seem doesn't help at all. Do you think this is a problem with VoodooRMI?
[Troubleshooting.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5168320/Troubleshooting.zip)

**Comment by Rohan200220** [comment]
I can't get my trackpad to work with any of the above voodoormi kexts.
I am uploading the log of the VoodooRMI 2 kext. I am using the first VoodooSMBUS kext
[log 2.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5171614/log.2.txt)

**Comment by Rohan200220** [comment]
I am using clover, do I need to add any patch in my config.plist for this to work?

**Comment by 1Revenger1** [comment]
@Rohan200220 you are getting some linking errors. What macOS version is this? I built these test kexts in Catalina 10.15.6, so if your running Mojave I may need to try and build it for an older version.

@LocTran016 huh, the log looks exactly the same as before.
SSDT-SBUS-MCHC will mess up VoodooSMBus so I'd avoid it.
Looks like it isn't able to communicate with the sensor again? That's so weird - I'll need to think on it. It appears to be aan issue which isn't always there which suggests I'm doing something wrong with memory, or something else is happening. Are you able to load/unload this repeatedly within macOS? It'd be good to see if it consistently breaks or doesn't.

**Comment by Rohan200220** [comment]
Yes i am running Mojave 10.14.6

**Comment by 1Revenger1** [comment]
[VoodooRMI.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5171650/VoodooRMI.zip)
This is from Github Actions, which is set to build in High Sierra. See if this version works. When getting logs, use the debug version

**Comment by Rohan200220** [comment]
Trackpad still not working.
[log 3.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5171700/log.3.txt)

**Comment by 1Revenger1** [comment]
Hmm, looks like the same issue as LocTran then. I don't have a version of VoodooSMBus for you to try in Mojave though. We'll see if it helps LocTran I guess.

**Comment by LocTran016** [comment]
> Edit: Oh LocTran, have you tried with the version of VoodooSMBus above?
No I haven't, let me try that then

**Comment by LocTran016** [comment]
I also try to load manually but the mouse doesn't work as well
[Log-1.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5172199/Log-1.txt)

**Comment by 1Revenger1** [comment]
Your kexts aren't owned by `root`, which is why they aren't loading manually. This should give more info about loading/unloading it: https://github.com/VoodooSMBus/VoodooRMI#loadingunloading

Do you mind trying this version? Turns out the table index may or may not have been zeroed out? Idk why it'd work for most people though tbh without it being zeroed out.
[VoodooRMI.kext 7.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5172599/VoodooRMI.kext.7.zip)

**Comment by LocTran016** [comment]
I don't know why the kext used to work magically. I also try the above kext but don't know why it doesn't work
[Troubleshooting.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5172997/Troubleshooting.zip)

**Comment by 1Revenger1** [comment]
I'm honestly not sure.
What I may try to do is take VoodooPS2SynapticsTouchpad and reduce it down to just do a hardware reset and see if it helps your trackpad at all.

**Comment by 1Revenger1** [comment]
[VoodooPS2Controller.kext.zip](https://github.com/VoodooSMBus/VoodooRMI/files/5178669/VoodooPS2Controller.kext.zip)
Do you mind trying out this build of VoodooPS2?
I modified VoodooPS2Trackpad to just do a hardware reset of the trackpad. So make sure to load VoodooPS2Controller/Keyboard/Trackpad rather than just the first 2. You will need to load VoodooRMI in macOS. This isn't a final solution, but I'd like to see if the trackpad is in some sort of weird state. I noticed that when I put the PS2 trackpad in a weird state on my device, or it was in the middle of resetting, it'd behave very similarly to yours.

**Comment by Rohan200220** [comment]
Trackpad not responding but Trackpad Preferences are being shown.
![Screenshot 2020-09-06 at 3 52 37 AM](https://user-images.githubusercontent.com/58611972/92314373-727bdc00-eff4-11ea-82d9-3596feaed167.png)
[Uploading Log 4.txt…]()

**Comment by 1Revenger1** [comment]
Trackpad Preference shows because VoodooPS2Trackpad still allows VoodooInput to attach (even if it's pretty useless lol)
I don't see any trace of VoodooSMBus/VoodooRMI in the log, are you loading those within macOS?

**Comment by Rohan200220** [comment]
No i removed them from my efi folder, should i add them back?
And how do i load them within macos?

**Comment by 1Revenger1** [comment]
https://github.com/VoodooSMBus/VoodooRMI#loadingunloading
I'm not exactly sure how to disable SIP when using Clover tbh. Should only need to be disabled though while your loading the kexts. It's important that the kexts are loaded once your at the desktop, as it appears that when it loads when injected is a bit to soon. I'll fix it at some point, but I'd like confirmation that this actually works for you guys first.

**Comment by Rohan200220** [comment]
I loaded them but the trackpad wasn’t functioning so i rebooted my laptop and its still not working.

**Comment by 1Revenger1** [comment]
Hard to tell without logs.
Also when you reboot, the kext gets unloaded, so you need to load it manually everytime you boot up if your doing it this way.

**Comment by Rohan200220** [comment]
Alright, I rebooted and loaded them again.
[log 6.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5178840/log.6.txt)

**Comment by 1Revenger1** [comment]
Huh, still not seeing anything. You sure that it's injecting properly? What's the output from `sudo kextutil -vvvv .....`

**Comment by Rohan200220** [comment]
I am getting this,

Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fe5256002c0 [0x7fffacf478f0]> { URL = "file:///Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext/", ID = "com.1Revenger1.RMISMBus" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fe5254446a0 [0x7fffacf478f0]> { URL = "file:///Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooSMBus.kext/", ID = "de.leo-labs.VoodooSMBus" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fe525500cf0 [0x7fffacf478f0]> { URL = "file:///Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooRMI.kext/", ID = "com.1Revenger1.VoodooRMI" }
Code Signing Failure: code signature is invalid
Warnings: 
    Dependency lacks appropriate value for OSBundleRequired and may not be available during early boot: 
        de.leo-labs.VoodooSMBus - OSBundleRequired not set

Warnings: 
    Dependency lacks appropriate value for OSBundleRequired and may not be available during early boot: 
        de.leo-labs.VoodooSMBus - OSBundleRequired not set

/Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
/Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext successfully loaded (or already loaded).
Invalid signature -67050 for kext <OSKext 0x7fe5256002c0 [0x7fffacf478f0]> { URL = "file:///Users/rohan/Downloads/VoodooRMI-975cbe0d/Debug/VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext/", ID = "com.1Revenger1.RMISMBus" }
Rohans-MacBook-Pro%

**Comment by 1Revenger1** [comment]
Hmm, if your loading from within macOS, `sudo log show --last boot | grep -i vrmi` should be reliable. Does that show anything?

**Comment by Rohan200220** [comment]
![Screenshot 2020-09-06 at 4 49 30 AM](https://user-images.githubusercontent.com/58611972/92314944-61cf6400-effc-11ea-8d3e-ac902d80b8d7.png)
When I write vrmi, nothing is shown
when I write voodoormi, I get this

**Comment by 1Revenger1** [comment]
Oh - try searching for RMISMbus as well, forgot that is technically a different kext from VoodooRMI.

**Comment by Rohan200220** [comment]
I get this when I write rmismbus
![Screenshot 2020-09-06 at 4 52 32 AM](https://user-images.githubusercontent.com/58611972/92314968-d7d3cb00-effc-11ea-94ab-aefa051f5130.png)

**Comment by 1Revenger1** [comment]
that's really weird. Try unloading and then loading it up again a couple times and see if you get an output. I've seen it not output anything before, though usually `sudo dmesg` is pretty reliable.

**Comment by Rohan200220** [comment]
![Screenshot 2020-09-06 at 4 56 42 AM](https://user-images.githubusercontent.com/58611972/92315013-647e8900-effd-11ea-9361-435d052c09d4.png)
it says unable to unload

**Comment by 1Revenger1** [comment]
You can only unload it once you've loaded it. When you reboot macOS, it automatically unloads. Make sure your grabbing logs after you load it, and are not restarting.

Past that, I'm not really sure what could be wrong, it doesn't seem like the kext is actually attempting to boot up.

**Comment by Rohan200220** [comment]
Ok, I loaded and unloaded it a couple of times, and I am sending you the loaded kexts log.
[log 7.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5178882/log.7.txt)

**Comment by 1Revenger1** [comment]
Hmm, If you check IOReg, is VoodooSMBus attaching to SBUS (or whatever ACPI name your SMBus chip has).
You should be able to have VoodooSMBus still injected by Clover/OpenCore. It's only VoodooRMI/RMISMBus that we're wanting to load within macOS itself.

**Comment by Rohan200220** [comment]
No I was injecting voodoosmbus also in macOS, I'll put voodoosmbus in clover and will send you the log

**Comment by Rohan200220** [comment]
Yes voodoosmbus is attaching and I also loaded the voodoormi kext within macOS.
![Screenshot 2020-09-06 at 8 39 19 AM](https://user-images.githubusercontent.com/58611972/92317281-a539ca80-f01c-11ea-830c-a5203624aca6.png)
[log8.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5179008/log8.txt)

**Comment by 1Revenger1** [comment]
Hmm, where did VoodooSMBus and VoodooRMI come from? I recently updated the version of VoodooSMBus needed - so if you got VoodooRMI recently, it needs VoodooSMBus version 3.0

**Comment by LocTran016** [comment]
I've tried to load manually but received this issue. I've run this in terminal:
```
LocTran@locs-macbook-air ~ % cd /Users/LocTran/Documents/Kext 
LocTran@locs-macbook-air Kext % sudo chown -R root:wheel *.kext
Password:
LocTran@locs-macbook-air Kext % sudo kextutil -vvvv -d VoodooRMI.kext -d VoodooSMBus.kext VoodooRMI.kext/Contents/PlugIns/RMISMBus.kext
```
But didn't help
[Log.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5179815/Log.txt)

**Comment by 1Revenger1** [comment]
It rejected VoodooSMBus and RMISMBus for invalid file permissions (i.e. the kexts weren't owned by root). I usually need to restart if it keeps saying their incorrect even after running `chown` multiple times, it's weird.

**Comment by Rohan200220** [comment]
I tried the latest VoodooRMI 1.1.0 Release, I just put the kexts in my EFI folder and deleted the Trackpad and Mouse kext from VoodooPS2Controller kext, rebooted and my trackpad started to work. But the trackpad is very sluggish and slow, but the gestures are working very well.
[log new.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5202533/log.new.txt)

**Comment by Rohan200220** [comment]
This is what I am getting in Ioreg
![Screenshot 2020-09-10 at 8 23 38 PM](https://user-images.githubusercontent.com/58611972/92749244-9304b700-f3a3-11ea-955c-892dbabb763f.png)

**Comment by 1Revenger1** [comment]
If you click on F11, how big does it say the trackpad is in millimeters?

Also, have you tested this across multiple reboots to see if it consistently works?

**Comment by Rohan200220** [comment]
Its not working when i rebooted :p 
Also it doesn’t do anything when i click on F11

**Comment by 1Revenger1** [comment]
Mind trying this build out? https://github.com/VoodooSMBus/VoodooRMI/runs/1097732807
Should be under artifacts and be built in High Sierra so it should work in Mojave.

**Comment by Rohan200220** [comment]
Mouse not working, I tried the debug version.
[new log 2.txt](https://github.com/VoodooSMBus/VoodooRMI/files/5203621/new.log.2.txt)

**Comment by 1Revenger1** [comment]
Hmm, can you try using the Ps2 kext from above and using VoodooPS2Trackpad, plus manually loading VoodooRMI from within macOS?

**Comment by Rohan200220** [comment]
yeah its better, where can I contact you?

**Comment by 1Revenger1** [comment]
oops, I meant gitter (not gutter). There should be a badge for it at the top of the README.

**Comment by proektus123** [comment]
Tested latest voodooSMBus 2.2 and VoodooRMI 1.1.0
It works fine on hp9470m 
![IMG_20200912_091627](https://user-images.githubusercontent.com/70524384/92988973-3d322b00-f4d9-11ea-90a6-87949003eeb8.jpg)

**Comment by proektus123** [comment]
![IMG_20200912_092344](https://user-images.githubusercontent.com/70524384/92989047-be89bd80-f4d9-11ea-85ff-24e46e2765a9.jpg)

**Comment by singhalrishi27** [comment]
Hello @proektus123 
I also have folio 9470m I'm having a non working trackpad with acidanthera ps2 also high cpu usage while on ideal can you please help me...
@singhalrishi27 on telegram
@singhalrishi27 on instagram
singhalrishi27@gmail.com my gmail please contact me bro please

**Comment by 1Revenger1** [comment]
Moved to #83

**Comment by lslqtz** [comment]
Same issue, I believe I have a Synaptics trackpad.
macOS 11.6.7, VoodooPS2 2.2.8, VoodooRMI 1.3.4.
![IMG_0187](https://user-images.githubusercontent.com/18650291/177914986-a742d45d-68bc-4007-aa71-2084d6f83ef3.jpeg)
![IMG_9302](https://user-images.githubusercontent.com/18650291/177915128-109de9c0-ab5a-440f-bf31-70b46dcf0568.png)
![IMG_0188](https://user-images.githubusercontent.com/18650291/177915258-c54926af-a8ed-4e95-9729-dda6ceadcf9a.jpeg)
