### ISSUE TITLE
[Feature Request] Palm detection for Trackpoint

### ISSUE THREAD

**Issue by SukkaW** [VoodooSMBus/VoodooRMI#35]
VoodooRMI already supports `DisableWhileTypingTimeout`. But it is also common that trackpad having accidental input when using trackpoint.

VoodooSMBus has a configuration `DisableWhileTrackpoint` but it has been removed from VoodooRMI bundled one. So I assume there is no Palm detection for trackpoint at this moment.

**Comment by 1Revenger1** [comment]
It uses the same value as DisableWhileTypingTimeout. It is there though.

Though, I would like to see about better detecting palm brushes without relying on any sort of timeout. I haven't thought of anything yet though.

**Comment by gimdh** [comment]
Personally, disabling Touchpad during trackpoint is good enough - No timeout yet dual input is prohibited.

**Comment by SukkaW** [comment]
@gimdh Considering this: It is very common to stop moving trackpoint while move the thumb toward "ThinkNav" for clicking.

**Comment by 1Revenger1** [comment]
Do you want a seperately controlled value then for the trackpoint disable? It currently just uses the value for DisableWhileTypingTimeout.

**Comment by gimdh** [comment]
Lenovo driver lets you configure touchpad deadzone where inputs initiated in the zone are ignored. Similar feature might help.

**Comment by 1Revenger1** [comment]
A feature like that may be better suited in VoodooInput itself, or possibly in a different touch library. Though, I doubt that'd be hard to implement other than for allowing the swiping gesture for notifications.

**Comment by gimdh** [comment]
Setting two rectangular or triangular deadzones from upper left and right corner could be a workaround.

I felt Apple's trackpad driver already has some palm rejection logic built in. (My VoodooI2C touchpad works great yet VoodooI2C has no workaround for palm rejection AFAIK.) Issue with trackpoint is it is not a touchpad and thus cannot stand on Apple's shoulder. So adding custom code to VoodooRMI seems good to me.
