### ISSUE TITLE
No two-finger gesture for notification center

### ISSUE THREAD

**Issue by EigenTom** [VoodooSMBus/VoodooRMI#54]
OpenCore 0.6.0, clean install macOS 10.15.6 Catalina, ThinkPad X1 Yoga 3rd, only two-finger swiping gesture for notification center don't work

**Comment by KirisameMarisaa** [comment]
The problem solved by update the kext to the latest version. 

Another question: I found the 2-finger zoom in/out gesture is not as sensitive as that under Windows 10. Is there any way to adjust its sensitivity? Thanks.
