### ISSUE TITLE
VoodooSMBus Dependency resolution failure

### ISSUE THREAD

**Issue by gimdh** [VoodooSMBus/VoodooRMI#62]
**Describe the bug**
When trying to load RMISMbus.kext following error occurs.

**To Reproduce**
Build with xcodebuild and try loading with kextutil.

**Expected behavior**
Loads properly

**Log**
```
Dependency Resolution Failures: 
    Kexts found for these libraries lack valid OSBundleCompatibleVersion: 
        de.leo-labs.VoodooSMBus
```

**Comment by gimdh** [comment]
I wonder if I used wrong VoodooSMBus. I tried latest release from
VoodooSMBus/VoodooSMBus and this repo.

**Comment by gimdh** [comment]
In **VoodooRMI/VoodooRMI/Transports/SMBus/Info.plist**, dependency is defined as follows
```
<key>OSBundleLibraries</key>
	<dict>
		<key>de.leo-labs.VoodooSMBus</key>
		<string>3.0</string>
```

However, VoodooSMBus does not have `OSBundleCompatibleVersion` key in info.plist. I added lines below, and now it loads properly.

```
        <key>OSBundleCompatibleVersion</key>
        <string>1.0</string>
```

**Comment by 1Revenger1** [comment]
The dev branch of VoodooSMBus has the correct version, which is what this is based on. I did indeed bump up the version, and I should have a release on Monday with the new voodooSMBus in it.

**Comment by gimdh** [comment]
I'll keep in mind that I should use dev branch. Thanks!
