### ISSUE TITLE
Failed to read SMBus version or Hid descriptor

### ISSUE THREAD

**Issue by tmbt78** [VoodooSMBus/VoodooRMI#70]
First time trying to use your kext
I would like to try the SMBus version because I've a SYNA3602.
I've applied the 4 patches in my config.plisti. SMBus is shown in ioReg and these 2 kexts are loaded: 
kextstat | grep "Voodoo"                                                                               
   77    1 0xffffff7f84b88000 0x17000    0x17000    de.leo-labs.VoodooSMBus (3.0) 3DAE1A14-5846-37EB-B491-D24A6765115A <63 13 6 5 3>
   83    1 0xffffff7f84b5d000 0x1f000    0x1f000    com.1Revenger1.VoodooRMI (1.1) CE1D615A-B3BF-344F-8266-7BB55F8C0CFC <63 6 5 3>

But the trackpad doesn't move and I've this error .. 

mattia@Mattias-MacBook-Pro ~ % sudo dmesg | grep VRMI                                                                                 
VRMI - Error: Error: Failed to read SMBus version. Code: 0xFFFFFFFA

Attached you will find a copy of my ioReg .. 
any suggestions ?
[Mattia’s MacBook Pro (1).zip](https://github.com/VoodooSMBus/VoodooRMI/files/5295042/Mattia.s.MacBook.Pro.1.zip)

If I try the VoodooI2C version I got this error : 
VRMI - Error: RMII2C::TPD1 Could not get valid HID descriptor
and these kexts are loaded : 
mattia@Mattias-MacBook-Pro ~ % kextstat | grep "Voodoo"
   50    1 0xffffff7f83f4d000 0xb000     0xb000     com.alexandred.VoodooI2CServices (1) DBFA5EBE-2783-30ED-8E39-5829C42D6832 <5 3>
   69    1 0xffffff7f83f58000 0x1a000    0x1a000    org.coolstar.VoodooGPIO (1.1) 652E2512-9BF1-35AD-85ED-880C9C5ABE9F <12 6 5 3>
   79    1 0xffffff7f840e0000 0x2e000    0x2e000    com.alexandred.VoodooI2C (2.4.4) F1763DBE-345B-3E9D-B3E4-208419389F6B <69 64 50 13 12 6 5 3 1>
  101    1 0xffffff7f84bc0000 0x1f000    0x1f000    com.1Revenger1.VoodooRMI (1.1) CE1D615A-B3BF-344F-8266-7BB55F8C0CFC <64 6 5 3>

**Comment by 1Revenger1** [comment]
Any reason to suggest it would work over SMBus? It may just not be connected over SMBus.

Also, this looks like a similar issue to what is being discussed in the VoodooI2C gitter. Going to guess that something is wrong with your ACPI.
