### ISSUE TITLE
Great with SYNA1202

### ISSUE THREAD

**Issue by FreeJHack** [VoodooSMBus/VoodooRMI#75]
Add SYNA1202 to compatible list.
It uses F12 & F30 (see picture)
Both trackpad buttons are correctly working.

All gestures are working except smart zoom (secondary click is simulated instead)

Really great job, buttons were not working before. Amazing.
Thanks
![Schermata 2020-10-10 alle 18 46 26](https://user-images.githubusercontent.com/22559967/95660739-142da600-0b2a-11eb-82e7-9af75af60aa9.png)

**Comment by 1Revenger1** [comment]
Thanks!
