### ISSUE TITLE
Trackpoint button does not work

### ISSUE THREAD

**Issue by gimdh** [VoodooSMBus/VoodooRMI#9]
**Describe the bug**
Trackpoint button does nothing

**To Reproduce**
Install driver. Corresponding patches are applied.

**Expected behavior**
Three trackpoint button works accordingly.

**Log**
N/A

Please note that my model has trackpoint buttons integrated to trackpad assembly, not keyboard. Thus it could send click signal via SMBus.

**Comment by 1Revenger1** [comment]
Looking at your other issue, sounds like it's VoodooI2c doing something. Make sure you don't have VoodooI2c loading.

**Comment by gimdh** [comment]
@1Revenger1 I never had VoodooI2C lodaed on this machine as VoodooPS2 was the only option to use trackpad until this great driver. And again, I checked thoroughly.

I also acked entire repo, and found no matching lines with that error message, but still removing this kext gets rid of error message.

**Comment by gimdh** [comment]
Duplicate of #8 
It seems both problem shares same cause. Closing this issue to focus on one.

**Comment by 1Revenger1** [comment]
This needs code implemented in F30 to commit buttons to F03.

**Comment by gimdh** [comment]
Updated code works great.
